version: "2"

run:
    timeout: 5m
    tests: true
    build-tags:
        - ""
    go: "1.25"

linters:
    disable:
        - funlen
        - wsl
        - godox
        - exhaustruct
        - nlreturn
        - lll
        - ireturn
        - gochecknoglobals
        - depguard
        - varnamelen
        - mnd
        - musttag
        - tagliatelle
        - godot
        - wrapcheck
